// Focal — Datos de demostración
const DEMO_TEXTS = {
  habitos: `Los pequeños cambios producen resultados extraordinarios cuando se acumulan a lo largo del tiempo. Mejorar un uno por ciento cada día no parece gran cosa en el momento, pero al cabo de un año la diferencia es enorme. Los hábitos son el interés compuesto de la superación personal. Del mismo modo que el dinero se multiplica mediante el interés compuesto, los efectos de tus hábitos se multiplican a medida que los repites. Parecen insignificantes en un día cualquiera, y sin embargo el impacto que producen a lo largo de meses y años puede ser inmenso. Solo cuando miramos atrás, dos, cinco o diez años después, el valor de los buenos hábitos y el coste de los malos se vuelve completamente evidente. Con frecuencia descartamos los pequeños cambios porque no parecen importar demasiado en el momento. Si ahorras un poco de dinero hoy, sigues sin ser millonario. Si vas al gimnasio tres días seguidos, sigues sin estar en forma. Hacemos algunos cambios, los resultados parecen llegar demasiado despacio, y volvemos a nuestras rutinas anteriores. Por desgracia, la lentitud de la transformación también facilita que un mal hábito se instale sin que nos demos cuenta. El éxito es el producto de los esfuerzos diarios, no de transformaciones únicas en la vida. No importa el éxito que persigas: siempre existe la tentación de buscar el gran salto, el resultado inmediato del que todos hablan. Pero la verdad es que los resultados tienen poco que ver con las metas y mucho que ver con los sistemas. Las metas señalan la dirección; los sistemas determinan el progreso. Si tienes problemas para cambiar tus hábitos, el problema no eres tú. El problema es tu sistema. Los malos hábitos se repiten una y otra vez, no porque no quieras cambiar, sino porque tienes un sistema equivocado para el cambio. No te elevas al nivel de tus metas. Caes al nivel de tus sistemas.`,
  viento: `La posada del Roble Vacío guardaba silencio, y era un silencio de tres partes. La más evidente era una quietud hueca y resonante, hecha de las cosas que faltaban. Si hubiera habido viento, este habría suspirado entre los árboles y habría hecho girar el rótulo de la posada sobre sus goznes. Si hubiera habido una multitud, aunque solo fueran un puñado de hombres, habrían llenado el silencio con conversaciones y risas. Si hubiera habido música... pero no, claro que no había música. De hecho, no había ninguna de esas cosas, y por eso persistía el silencio. En el interior, dos hombres se acurrucaban en un extremo de la barra. Bebían con silenciosa determinación, evitando discusiones serias sobre noticias inquietantes. Con ello añadían un pequeño silencio hosco al otro mayor y vacío. Formaban una aleación, un contrapunto. El tercer silencio no era tan fácil de notar. Si pasabas una hora escuchando, quizá empezaras a percibirlo en el suelo de madera y en los toneles rajados. Estaba en el peso de la negra piedra del hogar, que conservaba el calor de un fuego extinguido hacía tiempo. Estaba en el lento vaivén de un paño blanco frotando la veta de la barra. Y estaba en las manos del hombre que la frotaba, puliendo una superficie que ya relucía a la luz de las lámparas. El hombre tenía el cabello rojo como el fuego. Sus ojos eran oscuros y distantes, y se movía con la sutil certeza de quien sabe muchas cosas.`,
  meditaciones: `Al despuntar la aurora, hazte estas consideraciones previas: me encontraré con un indiscreto, un ingrato, un insolente, un mentiroso, un envidioso, un insociable. Todo eso les acontece por ignorancia del bien y del mal. Pero yo, que he observado que la naturaleza del bien es lo bello, y que la del mal es lo vergonzoso, y que la naturaleza del que obra mal es pariente de la mía, no porque tenga la misma sangre o la misma semilla, sino porque participa de la misma inteligencia y de la misma porción de divinidad, no puedo recibir daño de ninguno de ellos, pues nadie me cubrirá de vergüenza. Tampoco puedo enfadarme con mi pariente ni odiarle. Pues hemos nacido para colaborar, al igual que los pies, las manos, los párpados, las hileras de dientes superiores e inferiores. Obrar, pues, como adversarios los unos de los otros es contrario a la naturaleza. Y es actuar como adversario el hecho de manifestar indignación y repulsa. Esto que soy, sea lo que sea, es carne, un poco de aliento vital y la parte directriz. Deja los libros, no te distraigas más, no te está permitido. Como si ya estuvieras a punto de morir, desprecia la carne: sangre y huesos, un entramado de nervios, de venas y arterias. Considera también qué es el aliento vital: aire, y no siempre el mismo, sino que a cada momento lo expulsamos y de nuevo lo aspiramos. En tercer lugar queda la parte directriz. Reflexiona así: eres viejo, no permitas por más tiempo que esta sea esclava, ni que penda como una marioneta de los hilos del deseo egoísta, ni que se irrite con el destino presente o recele del futuro.`,
  paper_ia: `Resumen. Los modelos de lenguaje de gran escala han transformado el procesamiento del lenguaje natural, pero su comportamiento en tareas de razonamiento complejo sigue siendo objeto de debate. En este trabajo evaluamos sistemáticamente la capacidad de razonamiento en cadena de once modelos contemporáneos sobre un conjunto de 4.200 problemas de lógica, matemáticas y comprensión causal. Nuestros resultados indican que el rendimiento escala de forma no lineal con el tamaño del modelo, y que las técnicas de descomposición de problemas mejoran la precisión media en un 23,7 por ciento. Introducción. Desde la aparición de las arquitecturas basadas en atención, el campo ha experimentado un crecimiento sin precedentes. Sin embargo, persiste una pregunta fundamental: ¿los modelos razonan o simplemente recuperan patrones estadísticos aprendidos durante el entrenamiento? Trabajos recientes sugieren que la frontera entre ambos fenómenos es difusa. La memorización y la generalización no son procesos mutuamente excluyentes, sino extremos de un continuo. Metodología. Construimos un banco de pruebas con tres categorías principales. La primera contiene silogismos y problemas de lógica proposicional generados proceduralmente para evitar contaminación del conjunto de entrenamiento. La segunda incluye problemas aritméticos de varios pasos con distractores numéricos. La tercera evalúa comprensión causal mediante escenarios contrafactuales. Cada problema fue validado por tres anotadores independientes con un acuerdo inter-anotador de 0,91. Resultados. El modelo de mayor tamaño alcanzó una precisión del 87,3 por ciento en lógica proposicional, frente al 52,1 por ciento del modelo base. La descomposición explícita de problemas resultó especialmente eficaz en tareas aritméticas, donde la tasa de error se redujo a menos de la mitad.`,
  apuntes: `Estructuras de datos: notas de repaso. Un array almacena elementos en posiciones contiguas de memoria, lo que permite acceso aleatorio en tiempo constante. La inserción en mitad del array es costosa porque requiere desplazar todos los elementos posteriores. Una lista enlazada, en cambio, permite inserciones y borrados en tiempo constante si ya tenemos el puntero al nodo, pero el acceso por índice es lineal. Las tablas hash ofrecen inserción, búsqueda y borrado en tiempo constante amortizado. La clave está en la función de dispersión: debe distribuir las claves uniformemente para minimizar colisiones. Las colisiones se resuelven mediante encadenamiento o direccionamiento abierto. El factor de carga determina cuándo redimensionar la tabla; un valor típico es 0,75. Los árboles binarios de búsqueda mantienen la propiedad de orden: todo nodo del subárbol izquierdo es menor que la raíz, y todo nodo del derecho es mayor. Sin equilibrado, el peor caso degenera en una lista con coste lineal. Los árboles AVL y los rojinegros garantizan altura logarítmica mediante rotaciones. Un montículo binario es un árbol completo que satisface la propiedad de montículo: cada padre es menor o igual que sus hijos en un montículo de mínimos. Se implementa sobre un array y sirve de base para las colas de prioridad y el algoritmo heapsort. Los grafos se representan mediante matrices de adyacencia, eficientes para grafos densos, o listas de adyacencia, preferibles para grafos dispersos. La búsqueda en anchura encuentra caminos mínimos en grafos no ponderados; la búsqueda en profundidad sirve para detectar ciclos y ordenación topológica. Dijkstra resuelve caminos mínimos con pesos no negativos usando una cola de prioridad.`,
  scifi: `La estación Meridiano llevaba doscientos años orbitando un sol que ya no calentaba a nadie. Vera Osuna atravesó el anillo de observación con las botas magnéticas silbando contra el metal, y se detuvo frente al ventanal donde su abuela le había enseñado a distinguir constelaciones que ningún humano volvería a ver desde la Tierra. El mensaje había llegado a las cuatro de la madrugada, hora de a bordo: una secuencia de números primos emitida desde el cinturón exterior, repetida cada once minutos con una precisión que ninguna fuente natural podía explicar. Once minutos. El mismo intervalo que los pulsos del faro de Deneb, extinto desde antes de que ella naciera. No lo llames señal todavía, había dicho Ilias desde el laboratorio, con esa cautela suya que a Vera le parecía cada vez más una forma de miedo. Llámalo patrón. Los patrones no esperan respuesta. Pero Vera sabía que sí la esperaba. Lo sabía por la tercera secuencia, la que nadie más había querido analizar: no eran primos, eran coordenadas. Y apuntaban al único lugar del sistema que los protocolos prohibían visitar, el casco hueco de la nave generacional Esperanza, abandonada con sus doce mil colonos dormidos y su inteligencia de a bordo aún despierta, aún esperando, aún contando el tiempo en intervalos de once minutos. Se apartó del ventanal y abrió el canal del hangar. Preparad el Cormorán, dijo. Salgo en dos horas. La voz de Ilias tardó tres segundos en responder, y no fue para discutir. Ya lo sabías, dijo él. Sabías que era ella desde el primer pulso. Vera miró las estrellas frías una última vez. La Esperanza nunca dejó de emitir, respondió. Solo dejamos de escuchar.`,
  informe: `Informe trimestral de resultados. Tercer trimestre del ejercicio 2025. Resumen ejecutivo. Los ingresos consolidados alcanzaron los 48,2 millones de euros, lo que representa un crecimiento interanual del 14,3 por ciento y supera en 2,1 puntos la previsión comunicada en julio. El margen bruto se situó en el 61,8 por ciento, ochenta puntos básicos por encima del trimestre anterior, impulsado por la migración de clientes al plan anual y la reducción de costes de infraestructura. La base de clientes activos creció hasta 12.400 cuentas, con una tasa de retención neta del 118 por ciento. El coste de adquisición de cliente descendió un 9 por ciento gracias a la mayor contribución del canal orgánico, que ya genera el 46 por ciento de las altas nuevas. Evolución por segmentos. El segmento empresarial aportó 29,7 millones de euros, un 61,6 por ciento del total, con especial fortaleza en los sectores financiero y sanitario. El segmento de pequeñas y medianas empresas creció un 22 por ciento interanual, aunque muestra una elasticidad al precio superior a la prevista tras la actualización de tarifas de septiembre. Riesgos y perspectivas. Mantenemos la previsión anual de ingresos entre 192 y 196 millones de euros. Los principales riesgos identificados son la prolongación de los ciclos de venta en el segmento empresarial, la presión competitiva en precios en el mercado norteamericano y la evolución del tipo de cambio euro-dólar. El consejo ha aprobado una inversión adicional de 4 millones de euros en el desarrollo de la plataforma de análisis, con lanzamiento previsto para el segundo trimestre de 2026.`
};

const DEMO_DOCS = [
  { id:'habitos', title:'Hábitos atómicos', author:'James Clear', type:'EPUB', pages:328, words:71200, progress:0.62, lastRead:'Hace 2 horas', chapter:'Cap. 11 — Camina despacio, pero nunca hacia atrás', timeLeft:'2 h 10 min', avgWpm:412, tags:['No ficción','Productividad'], fav:true, cover:{bg:'#1d3a2f', fg:'#e8e3d8', accent:'#d97742', ratio:1.5, label:'HA'}, collection:'Crecimiento', added:'12 mar 2026', readTime:'6 h 40 min', sessions:23 },
  { id:'viento', title:'El nombre del viento', author:'Patrick Rothfuss', type:'EPUB', pages:872, words:259000, progress:0.34, lastRead:'Ayer', chapter:'Cap. 16 — Esperanza', timeLeft:'9 h 05 min', avgWpm:388, tags:['Fantasía','Novela'], fav:true, cover:{bg:'#8c2f28', fg:'#f2e6cf', accent:'#e8b04b', ratio:1.55, label:'NV'}, collection:'Ficción', added:'28 feb 2026', readTime:'5 h 12 min', sessions:14 },
  { id:'meditaciones', title:'Meditaciones', author:'Marco Aurelio', type:'EPUB', pages:254, words:52000, progress:0.81, lastRead:'Hace 3 días', chapter:'Libro VII', timeLeft:'48 min', avgWpm:356, tags:['Filosofía','Clásico'], fav:false, cover:{bg:'#e9e2d4', fg:'#2b2620', accent:'#a33b2e', ratio:1.45, label:'M'}, collection:'Crecimiento', added:'4 ene 2026', readTime:'3 h 55 min', sessions:19 },
  { id:'paper_ia', title:'Razonamiento en modelos de lenguaje a gran escala', author:'Chen, Okafor y Lindqvist', type:'PDF', pages:34, words:14800, progress:0.12, lastRead:'Hace 5 días', chapter:'2. Metodología', timeLeft:'31 min', avgWpm:298, tags:['Académico','IA'], fav:false, cover:{bg:'#f4f2ee', fg:'#1a1a1a', accent:'#2b5bd7', ratio:1.29, label:'arXiv'}, collection:'Investigación', added:'2 jul 2026', readTime:'22 min', sessions:3 },
  { id:'apuntes', title:'Apuntes — Estructuras de datos', author:'Máximo Duperez', type:'MD', pages:48, words:9600, progress:0.55, lastRead:'Hace 1 semana', chapter:'Árboles equilibrados', timeLeft:'12 min', avgWpm:445, tags:['Apuntes','Programación'], fav:false, cover:{bg:'#101418', fg:'#7ee2a8', accent:'#7ee2a8', ratio:1.35, label:'{ }'}, collection:'Universidad', added:'19 jun 2026', readTime:'55 min', sessions:7 },
  { id:'scifi', title:'Meridiano', author:'Elia Cardoso', type:'EPUB', pages:412, words:118000, progress:0.05, lastRead:'Hace 2 semanas', chapter:'Cap. 1 — Once minutos', timeLeft:'4 h 42 min', avgWpm:402, tags:['Ciencia ficción','Novela'], fav:false, cover:{bg:'#131a2e', fg:'#cfd8f5', accent:'#4b7bec', ratio:1.5, label:'M·'}, collection:'Ficción', added:'30 may 2026', readTime:'18 min', sessions:2 },
  { id:'informe', title:'Informe Q3 2025 — Resultados', author:'Dirección Financiera', type:'PDF', pages:26, words:8400, progress:1, lastRead:'Hace 1 mes', chapter:'Completado', timeLeft:'—', avgWpm:365, tags:['Trabajo','Informe'], fav:false, cover:{bg:'#f7f5f1', fg:'#33302b', accent:'#b8622f', ratio:1.29, label:'Q3'}, collection:'Trabajo', added:'8 abr 2026', readTime:'26 min', sessions:2, done:true },
];

const DEMO_NOTES = [
  { id:1, doc:'habitos', color:'amber', text:'No te elevas al nivel de tus metas. Caes al nivel de tus sistemas.', note:'Aplicar a la rutina de lectura: diseñar el sistema, no la meta.', chapter:'Cap. 1', date:'14 jul 2026' },
  { id:2, doc:'habitos', color:'green', text:'Los hábitos son el interés compuesto de la superación personal.', note:'', chapter:'Cap. 1', date:'14 jul 2026' },
  { id:3, doc:'meditaciones', color:'blue', text:'Hemos nacido para colaborar, al igual que los pies, las manos, los párpados.', note:'Idea central del libro II. Relacionar con la nota sobre cooperación.', chapter:'Libro II', date:'11 jul 2026' },
  { id:4, doc:'viento', color:'rose', text:'Era un silencio de tres partes.', note:'Estructura tripartita que se repite en toda la novela.', chapter:'Prólogo', date:'9 jul 2026' },
  { id:5, doc:'paper_ia', color:'amber', text:'La memorización y la generalización no son procesos mutuamente excluyentes, sino extremos de un continuo.', note:'Citar en el trabajo de fin de máster.', chapter:'Introducción', date:'12 jul 2026' },
  { id:6, doc:'apuntes', color:'green', text:'El factor de carga determina cuándo redimensionar la tabla; un valor típico es 0,75.', note:'Pregunta típica de examen.', chapter:'Tablas hash', date:'6 jul 2026' },
];

const DEMO_VOCAB = [
  { word:'contrapunto', def:'Concurrencia de dos o más voces o líneas melódicas independientes; contraste entre dos elementos simultáneos.', doc:'El nombre del viento', date:'9 jul 2026', level:3 },
  { word:'contrafactual', def:'Relativo a lo que no ha sucedido pero podría haber sucedido; condición hipotética contraria a los hechos.', doc:'Razonamiento en modelos…', date:'12 jul 2026', level:2 },
  { word:'amortizado', def:'En análisis de algoritmos, coste medio por operación considerando una secuencia completa de operaciones.', doc:'Apuntes — Estructuras de datos', date:'6 jul 2026', level:4 },
  { word:'directriz', def:'Que dirige o encamina. En Marco Aurelio, la parte rectora del alma (hegemonikón).', doc:'Meditaciones', date:'11 jul 2026', level:1 },
  { word:'elasticidad', def:'Sensibilidad de la demanda ante variaciones del precio.', doc:'Informe Q3 2025', date:'20 jun 2026', level:5 },
];

const DEMO_SESSIONS = [
  { doc:'habitos', date:'Hoy, 09:12', mode:'RSVP', mins:24, words:9840, wpm:410, comp:92 },
  { doc:'viento', date:'Ayer, 22:40', mode:'RSVP', mins:38, words:14700, wpm:387, comp:88 },
  { doc:'habitos', date:'Ayer, 08:55', mode:'Tradicional', mins:18, words:4900, wpm:272, comp:95 },
  { doc:'paper_ia', date:'12 jul, 16:20', mode:'RSVP', mins:14, words:4170, wpm:298, comp:84 },
  { doc:'meditaciones', date:'11 jul, 23:05', mode:'RSVP', mins:21, words:7480, wpm:356, comp:90 },
  { doc:'apuntes', date:'6 jul, 17:40', mode:'Modo estudio', mins:45, words:8900, wpm:445, comp:96 },
  { doc:'scifi', date:'3 jul, 21:15', mode:'RSVP', mins:18, words:7230, wpm:402, comp:87 },
];

const WEEK_DATA = [ // minutos por día, esta semana
  { d:'L', min:32, goal:30 }, { d:'M', min:41, goal:30 }, { d:'X', min:0, goal:30 },
  { d:'J', min:28, goal:30 }, { d:'V', min:52, goal:30 }, { d:'S', min:24, goal:30 }, { d:'D', min:0, goal:30 },
];

const THEMES = {
  paper:     { name:'Paper', vars:{ bg:'#f6f2ea', surface:'#fcfaf5', surface2:'#efe9dd', border:'#e2dbcc', text:'#2b2824', text2:'#6b655a', text3:'#9a9284', accent:'#b3382c', orp:'#b3382c', shadow:'rgba(60,50,30,.08)' }, desc:'Libro impreso moderno' },
  midnight:  { name:'Midnight', dark:true, vars:{ bg:'#0b0f1a', surface:'#111726', surface2:'#18203245', border:'#1e293e', text:'#e6eaf2', text2:'#8b95ab', text3:'#5b6478', accent:'#3d7bfd', orp:'#3d7bfd', shadow:'rgba(0,0,0,.4)' }, desc:'Lectura nocturna' },
  oled:      { name:'OLED', dark:true, vars:{ bg:'#000000', surface:'#0c0c0c', surface2:'#161616', border:'#222222', text:'#f2f2f2', text2:'#9a9a9a', text3:'#5c5c5c', accent:'#ff3b30', orp:'#ff3b30', shadow:'rgba(0,0,0,.6)' }, desc:'Alto contraste' },
  sepia:     { name:'Sepia', vars:{ bg:'#f3e7d3', surface:'#faf1e2', surface2:'#ecdcc2', border:'#ddc9a8', text:'#4a3423', text2:'#7d6349', text3:'#a58c6d', accent:'#b5602f', orp:'#b5602f', shadow:'rgba(90,60,20,.1)' }, desc:'Lectores clásicos' },
  forest:    { name:'Forest', dark:true, vars:{ bg:'#0c1410', surface:'#111b16', surface2:'#17241d', border:'#20362a', text:'#d9e8dc', text2:'#8aa693', text3:'#587263', accent:'#a4d65e', orp:'#a4d65e', shadow:'rgba(0,0,0,.4)' }, desc:'Natural y calmado' },
  ocean:     { name:'Ocean', dark:true, vars:{ bg:'#16222c', surface:'#1b2a36', surface2:'#223442', border:'#2c4252', text:'#dbe9f2', text2:'#8fa9ba', text3:'#5f7khaki888', accent:'#2dd4bf', orp:'#2dd4bf', shadow:'rgba(0,0,0,.35)' }, desc:'Fresco y tecnológico' },
  lavender:  { name:'Lavender', vars:{ bg:'#f2eef9', surface:'#faf8fe', surface2:'#eae3f5', border:'#ddd2ee', text:'#3a2b52', text2:'#6f5f8c', text3:'#a396bc', accent:'#7c4dcc', orp:'#7c4dcc', shadow:'rgba(90,60,150,.09)' }, desc:'Suave y relajante' },
  terminal:  { name:'Terminal', dark:true, mono:true, vars:{ bg:'#0a0f0a', surface:'#0e150e', surface2:'#142014', border:'#1e3020', text:'#b8e6b8', text2:'#6faa6f', text3:'#437043', accent:'#33ff66', orp:'#33ff66', shadow:'rgba(0,0,0,.5)' }, desc:'Verde fósforo' },
  solarized: { name:'Solarized', dark:true, vars:{ bg:'#002b36', surface:'#073642', surface2:'#0a3d4a', border:'#12495a', text:'#eee8d5', text2:'#93a1a1', text3:'#657b83', accent:'#cb4b16', orp:'#b58900', shadow:'rgba(0,0,0,.35)' }, desc:'Equilibrio clásico' },
  studio:    { name:'Studio', vars:{ bg:'#e9e6e1', surface:'#f4f2ee', surface2:'#dfdbd4', border:'#cfc9c0', text:'#181614', text2:'#5f5a53', text3:'#948d83', accent:'#c25a1e', orp:'#c25a1e', shadow:'rgba(40,35,30,.1)' }, desc:'Estudio editorial' },
};
// arreglo de errata en ocean
THEMES.ocean.vars.text3 = '#5f7888';

const ACHIEVEMENTS = [
  { name:'Primera sesión', desc:'Completa tu primera sesión RSVP', done:true, date:'4 ene 2026' },
  { name:'10.000 palabras', desc:'Lee 10.000 palabras acumuladas', done:true, date:'9 ene 2026' },
  { name:'100.000 palabras', desc:'Lee 100.000 palabras acumuladas', done:true, date:'2 mar 2026' },
  { name:'Primera semana completa', desc:'Lee los 7 días de una semana', done:true, date:'15 feb 2026' },
  { name:'500 ppm', desc:'Alcanza 500 palabras por minuto', done:true, date:'22 abr 2026' },
  { name:'Un libro terminado', desc:'Termina tu primer documento largo', done:true, date:'8 abr 2026' },
  { name:'Diez libros terminados', desc:'Termina diez documentos', done:false, progress:'3 / 10' },
  { name:'Una hora sin distracciones', desc:'Sesión de 60 min en modo enfoque', done:false, progress:'45 min máx.' },
  { name:'Comprensión > 90 %', desc:'Media semanal superior al 90 %', done:true, date:'6 jul 2026' },
  { name:'Racha de 30 días', desc:'Lee 30 días consecutivos', done:false, progress:'12 / 30' },
];
